name: Deploy Contract

on:
  push:
    branches:
      - Branch1
    paths:
      - 'contracts/**'
      - 'transparent/**'
      - 'upgrade/**'
    
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
    deploy:
      if: contains(github.event.head_commit.modified, 'contracts/')
      name: Deploy Contract
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node:version: current
          
      - name: Install depndencies 
        run: npm ci
        
      - name: Installing hardhat
        run: npm install -g hardhat
        
      - name: Compile contract
        run: npx hardhat compile

      - name: Test contract
        run: npx hardhat test

      - name: Deploy Contract
        runs-on: ubuntu-latest

      - name: Deploy contract
        run: npx hardhat run scripts/deploy_contract.js --network volta

    deploy-proxy:
      runs-on: ubuntu-latest
      if: contains(github.event.head_commit.modified, 'proxy/')
      needs: deploy
      steps:
      - name: Deploy proxy
        run: npx hardhat run scripts/deployProxy.js --network volta
