name: Automated Deployment of Smart Contracts

on: 
  #push:
    #branches:
      #- main
  workflow_dispatch:
  #  inputs:      
   #     network:
#          name: Network to Deploy to
#          type: choice
#          description: 'Enter the network to deploy to: EWC or Volta'
#          options:
#          - volta
#          - ewc
#          required: true
#          default: volta
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}


jobs:

  Dev:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node:version: current
          
      - name: Install depndencies 
        run: npm ci
        
      - name: Installing hardhat
        run: npm install -g hardhat
        
      - name: Compile contract
        run: npx hardhat compile

      - name: Test contract
        run: npx hardhat test

      - name: Deploy contract
        run: npx hardhat run scripts/deploy.js --network volta
        
  Prod:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Test
        run: |
          echo "Production Env!"
